### ISSUE TITLE
Geocoder not getting correct country

### ISSUE THREAD

**Issue by Miccia94** [daviddrysdale/python-phonenumbers#185] opened 2021-01-15 14:43 UTC
As for title looks like im getting some issue with getting mobile italy country:

```pycon
>>> x = phonenumbers.parse("+39346555555", None)
>>> geocoder.country_name_for_number(x,"en")
''
>>>
```

Works fine here https://libphonenumber.appspot.com/phonenumberparser?number=%2B39346555555
Also noticed that just putting a 0 after the coutry code works fine:

```
>>> x = phonenumbers.parse("+390346555555", None)
>>> geocoder.country_name_for_number(x,"en")
'Italy'
>>>
```

Thanks for the support

**Comment by daviddrysdale** [comment] 2021-01-15 16:10
This is basically a duplicate of #174 &ndash; the appspot demo doesn't show the output of this function under "Phone Number region" (not least because it's `private` in the Java implementation).  

To see similar behaviour from the Java code, look at the "Location" information near the bottom:

 - https://libphonenumber.appspot.com/phonenumberparser?number=%2B39346555555 has `""`
 - https://libphonenumber.appspot.com/phonenumberparser?number=%2B390346555555 has `"Bergamo"`

(I suspect I should remove `country_name_for_number` to avoid more confusion.)

**Closed as completed by daviddrysdale** 2021-01-15 16:10 UTC
Labels: wai, help
